version: '3'

tasks:
  dev:
    desc: Run full-stack development (backend + frontend)
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: Run backend development server
    cmds:
      - go run cmd/maxx/main.go

  dev:frontend:
    desc: Run frontend development server
    dir: web
    cmds:
      - npm run dev

  dev:desktop:
    desc: Run Wails desktop application in development mode
    cmds:
      - wails dev

  install:
    desc: Install all dependencies
    cmds:
      - task: install:frontend
      - task: install:wails

  install:frontend:
    desc: Install frontend dependencies
    dir: web
    cmds:
      - npm install

  install:wails:
    desc: Install Wails CLI
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest

  build:
    desc: Build complete application (frontend + backend)
    cmds:
      - task: build:frontend
      - task: build:backend

  build:frontend:
    desc: Build frontend
    dir: web
    cmds:
      - npm run build

  build:backend:
    desc: Build backend binary
    cmds:
      - go build -o maxx cmd/maxx/main.go

  build:desktop:
    desc: Build Wails desktop application
    deps: [build:frontend]
    cmds:
      - wails build

  build:desktop:windows:
    desc: Build Wails desktop application for Windows
    deps: [build:frontend]
    cmds:
      - wails build -platform windows/amd64

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf web/dist
      - rm -rf build
      - rm -f maxx
