// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCooldown(arg1) {
  return window['go']['desktop']['DesktopApp']['ClearCooldown'](arg1);
}

export function CopyServerAddress() {
  return window['go']['desktop']['DesktopApp']['CopyServerAddress']();
}

export function CreateProject(arg1) {
  return window['go']['desktop']['DesktopApp']['CreateProject'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['desktop']['DesktopApp']['CreateProvider'](arg1);
}

export function CreateRetryConfig(arg1) {
  return window['go']['desktop']['DesktopApp']['CreateRetryConfig'](arg1);
}

export function CreateRoute(arg1) {
  return window['go']['desktop']['DesktopApp']['CreateRoute'](arg1);
}

export function CreateRoutingStrategy(arg1) {
  return window['go']['desktop']['DesktopApp']['CreateRoutingStrategy'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['desktop']['DesktopApp']['DeleteProject'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['desktop']['DesktopApp']['DeleteProvider'](arg1);
}

export function DeleteRetryConfig(arg1) {
  return window['go']['desktop']['DesktopApp']['DeleteRetryConfig'](arg1);
}

export function DeleteRoute(arg1) {
  return window['go']['desktop']['DesktopApp']['DeleteRoute'](arg1);
}

export function DeleteRoutingStrategy(arg1) {
  return window['go']['desktop']['DesktopApp']['DeleteRoutingStrategy'](arg1);
}

export function DeleteSetting(arg1) {
  return window['go']['desktop']['DesktopApp']['DeleteSetting'](arg1);
}

export function ExportProviders() {
  return window['go']['desktop']['DesktopApp']['ExportProviders']();
}

export function GetAntigravityProviderQuota(arg1, arg2) {
  return window['go']['desktop']['DesktopApp']['GetAntigravityProviderQuota'](arg1, arg2);
}

export function GetCooldowns() {
  return window['go']['desktop']['DesktopApp']['GetCooldowns']();
}

export function GetLogs(arg1) {
  return window['go']['desktop']['DesktopApp']['GetLogs'](arg1);
}

export function GetProject(arg1) {
  return window['go']['desktop']['DesktopApp']['GetProject'](arg1);
}

export function GetProjectBySlug(arg1) {
  return window['go']['desktop']['DesktopApp']['GetProjectBySlug'](arg1);
}

export function GetProjects() {
  return window['go']['desktop']['DesktopApp']['GetProjects']();
}

export function GetProvider(arg1) {
  return window['go']['desktop']['DesktopApp']['GetProvider'](arg1);
}

export function GetProviderStats(arg1, arg2) {
  return window['go']['desktop']['DesktopApp']['GetProviderStats'](arg1, arg2);
}

export function GetProviders() {
  return window['go']['desktop']['DesktopApp']['GetProviders']();
}

export function GetProxyRequest(arg1) {
  return window['go']['desktop']['DesktopApp']['GetProxyRequest'](arg1);
}

export function GetProxyRequests(arg1, arg2) {
  return window['go']['desktop']['DesktopApp']['GetProxyRequests'](arg1, arg2);
}

export function GetProxyRequestsCount() {
  return window['go']['desktop']['DesktopApp']['GetProxyRequestsCount']();
}

export function GetProxyRequestsCursor(arg1, arg2, arg3) {
  return window['go']['desktop']['DesktopApp']['GetProxyRequestsCursor'](arg1, arg2, arg3);
}

export function GetProxyStatus() {
  return window['go']['desktop']['DesktopApp']['GetProxyStatus']();
}

export function GetProxyUpstreamAttempts(arg1) {
  return window['go']['desktop']['DesktopApp']['GetProxyUpstreamAttempts'](arg1);
}

export function GetRetryConfig(arg1) {
  return window['go']['desktop']['DesktopApp']['GetRetryConfig'](arg1);
}

export function GetRetryConfigs() {
  return window['go']['desktop']['DesktopApp']['GetRetryConfigs']();
}

export function GetRoute(arg1) {
  return window['go']['desktop']['DesktopApp']['GetRoute'](arg1);
}

export function GetRoutes() {
  return window['go']['desktop']['DesktopApp']['GetRoutes']();
}

export function GetRoutingStrategies() {
  return window['go']['desktop']['DesktopApp']['GetRoutingStrategies']();
}

export function GetRoutingStrategy(arg1) {
  return window['go']['desktop']['DesktopApp']['GetRoutingStrategy'](arg1);
}

export function GetServerAddress() {
  return window['go']['desktop']['DesktopApp']['GetServerAddress']();
}

export function GetServerStatus() {
  return window['go']['desktop']['DesktopApp']['GetServerStatus']();
}

export function GetSessions() {
  return window['go']['desktop']['DesktopApp']['GetSessions']();
}

export function GetSetting(arg1) {
  return window['go']['desktop']['DesktopApp']['GetSetting'](arg1);
}

export function GetSettings() {
  return window['go']['desktop']['DesktopApp']['GetSettings']();
}

export function HideWindow() {
  return window['go']['desktop']['DesktopApp']['HideWindow']();
}

export function ImportProviders(arg1) {
  return window['go']['desktop']['DesktopApp']['ImportProviders'](arg1);
}

export function IsAutoStartEnabled() {
  return window['go']['desktop']['DesktopApp']['IsAutoStartEnabled']();
}

export function IsTrayMode() {
  return window['go']['desktop']['DesktopApp']['IsTrayMode']();
}

export function OpenDataDir() {
  return window['go']['desktop']['DesktopApp']['OpenDataDir']();
}

export function OpenLogFile() {
  return window['go']['desktop']['DesktopApp']['OpenLogFile']();
}

export function Quit() {
  return window['go']['desktop']['DesktopApp']['Quit']();
}

export function RestartServer() {
  return window['go']['desktop']['DesktopApp']['RestartServer']();
}

export function SetAutoStart(arg1) {
  return window['go']['desktop']['DesktopApp']['SetAutoStart'](arg1);
}

export function SetTrayMode(arg1) {
  return window['go']['desktop']['DesktopApp']['SetTrayMode'](arg1);
}

export function ShowWindow() {
  return window['go']['desktop']['DesktopApp']['ShowWindow']();
}

export function StartServer() {
  return window['go']['desktop']['DesktopApp']['StartServer']();
}

export function StopServer() {
  return window['go']['desktop']['DesktopApp']['StopServer']();
}

export function UpdateProject(arg1) {
  return window['go']['desktop']['DesktopApp']['UpdateProject'](arg1);
}

export function UpdateProvider(arg1) {
  return window['go']['desktop']['DesktopApp']['UpdateProvider'](arg1);
}

export function UpdateRetryConfig(arg1) {
  return window['go']['desktop']['DesktopApp']['UpdateRetryConfig'](arg1);
}

export function UpdateRoute(arg1) {
  return window['go']['desktop']['DesktopApp']['UpdateRoute'](arg1);
}

export function UpdateRoutingStrategy(arg1) {
  return window['go']['desktop']['DesktopApp']['UpdateRoutingStrategy'](arg1);
}

export function UpdateSessionProject(arg1, arg2) {
  return window['go']['desktop']['DesktopApp']['UpdateSessionProject'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['desktop']['DesktopApp']['UpdateSetting'](arg1, arg2);
}

export function ValidateAntigravityToken(arg1) {
  return window['go']['desktop']['DesktopApp']['ValidateAntigravityToken'](arg1);
}

export function ValidateAntigravityTokenText(arg1) {
  return window['go']['desktop']['DesktopApp']['ValidateAntigravityTokenText'](arg1);
}

export function ValidateAntigravityTokens(arg1) {
  return window['go']['desktop']['DesktopApp']['ValidateAntigravityTokens'](arg1);
}
