// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {desktop} from '../models';
import {service} from '../models';

export function ClearCooldown(arg1:number):Promise<void>;

export function CopyServerAddress():Promise<void>;

export function CreateProject(arg1:domain.Project):Promise<void>;

export function CreateProvider(arg1:domain.Provider):Promise<void>;

export function CreateRetryConfig(arg1:domain.RetryConfig):Promise<void>;

export function CreateRoute(arg1:domain.Route):Promise<void>;

export function CreateRoutingStrategy(arg1:domain.RoutingStrategy):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteProvider(arg1:number):Promise<void>;

export function DeleteRetryConfig(arg1:number):Promise<void>;

export function DeleteRoute(arg1:number):Promise<void>;

export function DeleteRoutingStrategy(arg1:number):Promise<void>;

export function DeleteSetting(arg1:string):Promise<void>;

export function ExportProviders():Promise<Array<domain.Provider>>;

export function GetAntigravityProviderQuota(arg1:number,arg2:boolean):Promise<desktop.AntigravityQuotaData>;

export function GetCooldowns():Promise<Array<domain.Cooldown>>;

export function GetLogs(arg1:number):Promise<service.LogsResult>;

export function GetProject(arg1:number):Promise<domain.Project>;

export function GetProjectBySlug(arg1:string):Promise<domain.Project>;

export function GetProjects():Promise<Array<domain.Project>>;

export function GetProvider(arg1:number):Promise<domain.Provider>;

export function GetProviderStats(arg1:string,arg2:number):Promise<Record<number, domain.ProviderStats>>;

export function GetProviders():Promise<Array<domain.Provider>>;

export function GetProxyRequest(arg1:number):Promise<domain.ProxyRequest>;

export function GetProxyRequests(arg1:number,arg2:number):Promise<Array<domain.ProxyRequest>>;

export function GetProxyRequestsCount():Promise<number>;

export function GetProxyRequestsCursor(arg1:number,arg2:number,arg3:number):Promise<service.CursorPaginationResult>;

export function GetProxyStatus():Promise<service.ProxyStatus>;

export function GetProxyUpstreamAttempts(arg1:number):Promise<Array<domain.ProxyUpstreamAttempt>>;

export function GetRetryConfig(arg1:number):Promise<domain.RetryConfig>;

export function GetRetryConfigs():Promise<Array<domain.RetryConfig>>;

export function GetRoute(arg1:number):Promise<domain.Route>;

export function GetRoutes():Promise<Array<domain.Route>>;

export function GetRoutingStrategies():Promise<Array<domain.RoutingStrategy>>;

export function GetRoutingStrategy(arg1:number):Promise<domain.RoutingStrategy>;

export function GetServerAddress():Promise<string>;

export function GetServerStatus():Promise<string>;

export function GetSessions():Promise<Array<domain.Session>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSettings():Promise<Record<string, string>>;

export function HideWindow():Promise<void>;

export function ImportProviders(arg1:Array<domain.Provider>):Promise<service.ImportResult>;

export function IsAutoStartEnabled():Promise<boolean>;

export function IsTrayMode():Promise<boolean>;

export function OpenDataDir():Promise<void>;

export function OpenLogFile():Promise<void>;

export function Quit():Promise<void>;

export function RestartServer():Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetTrayMode(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UpdateProject(arg1:domain.Project):Promise<void>;

export function UpdateProvider(arg1:domain.Provider):Promise<void>;

export function UpdateRetryConfig(arg1:domain.RetryConfig):Promise<void>;

export function UpdateRoute(arg1:domain.Route):Promise<void>;

export function UpdateRoutingStrategy(arg1:domain.RoutingStrategy):Promise<void>;

export function UpdateSessionProject(arg1:string,arg2:number):Promise<service.UpdateSessionProjectResult>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;

export function ValidateAntigravityToken(arg1:string):Promise<desktop.AntigravityTokenValidationResult>;

export function ValidateAntigravityTokenText(arg1:string):Promise<desktop.AntigravityBatchValidationResult>;

export function ValidateAntigravityTokens(arg1:Array<string>):Promise<desktop.AntigravityBatchValidationResult>;
